source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'MeliMPExercise' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
# use_frameworks!

# Pods for MeliMPExercise
pod 'AFNetworking', '3.0'
pod 'SDWebImage', '3.8'
pod 'AnimatedLoadingView', '0.0.1'

end
